### ISSUE TITLE
Driver crash when using an entrypoint

### ISSUE THREAD

**Issue by volfco** [hashicorp/nomad-driver-podman#60]
I'm trying to spawn a docker container. My taks is as follows:
```
    task "frontend" {
      driver = "podman"
      config {
        image = "docker-hub/prod/telescope-frontend:8d2059f411a4"
        entrypoint = "/entrypoint.sh"
        port_map = {
          http = 80
        }
    }
```

I tried to specify the entrypoint because I was getting `stderr F env: can't execute 'sh': No such file or directory` type error when I spawned it. Adding it caused the plugin to crash with the following error:

```
 2020-08-18T20:56:32.721Z [DEBUG] client.driver_mgr: waiting for RPC address: driver=podman path=/opt/nomad/plugins/nomad-driver-podman
 2020-08-18T20:56:32.731Z [DEBUG] client.driver_mgr: using plugin: driver=podman version=2
 2020-08-18T20:56:32.731Z [DEBUG] client.driver_mgr.nomad-driver-podman: plugin address: driver=podman address=/tmp/plugin581382622 network=unix timestamp=2020-08-18T20:56:32.730Z
 2020-08-18T20:56:32.738Z [DEBUG] client.driver_mgr.nomad-driver-podman: Get podman info: driver=podman @module=podmanClient timestamp=2020-08-18T20:56:32.738Z
 2020-08-18T20:56:32.742Z [DEBUG] client.driver_mgr.nomad-driver-podman: Inspect image: driver=podman @module=podmanClient image=docker-hub/prod/telescope-frontend:8d2059f411a4 timestamp=2020-08-18T20:56:32.739Z
 2020-08-18T20:56:32.742Z [DEBUG] client.driver_mgr.nomad-driver-podman: Image created: driver=podman img_id=8d2059f411a41384ee67194c46cb2570fcb749e7c02fd99c052ef8fd1cbbf3de @module=podman config="map[Cmd:[sh /entrypoint.sh] Entrypoint:[/docker-entrypoint.sh] Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/u>
 2020-08-18T20:56:32.743Z [DEBUG] client.driver_mgr.nomad-driver-podman: created/pulled image: driver=podman @module=podman img_id=8d2059f411a41384ee67194c46cb2570fcb749e7c02fd99c052ef8fd1cbbf3de timestamp=2020-08-18T20:56:32.742Z
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman: panic: runtime error: invalid memory address or nil pointer dereference: driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb57e32]: driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman: : driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman: goroutine 34 [running]:: driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman: main.(*Driver).StartTask(0xc0002d8230, 0xc000192200, 0xc0001c2e00, 0x644, 0x644, 0xccd8c0): driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman:         /home/colum/workspace/terraform/puppet/tmp/nomad-driver-podman-0.1.0/driver.go:372 +0x3c2: driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman: github.com/hashicorp/nomad/plugins/drivers.(*driverPluginServer).StartTask(0xc00028c860, 0xeb1780, 0xc0001827b0, 0xc0001827e0, 0xc00028c860, 0xc0001827b0, 0xc000061ba0): driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman:         /home/colum/workspace/terraform/puppet/tmp/nomad-driver-podman-0.1.0/build/pkg/mod/github.com/hashicorp/nomad@v0.11.3-0.20200630133459-42c2ee4448c8/plugins/drivers/server.go:105 +0x60: driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman: github.com/hashicorp/nomad/plugins/drivers/proto._Driver_StartTask_Handler(0xd0aa20, 0xc00028c860, 0xeb1780, 0xc0001827b0, 0xc0001805a0, 0x0, 0xeb1780, 0xc0001827b0, 0xc0001c2e00, 0x644): driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman:         /home/colum/workspace/terraform/puppet/tmp/nomad-driver-podman-0.1.0/build/pkg/mod/github.com/hashicorp/nomad@v0.11.3-0.20200630133459-42c2ee4448c8/plugins/drivers/proto/driver.pb.go:4260 +0x217: driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002d64e0, 0xebf940, 0xc000001980, 0xc000192100, 0xc0002bdb60, 0x1457668, 0x0, 0x0, 0x0): driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman:         /home/colum/workspace/terraform/puppet/tmp/nomad-driver-podman-0.1.0/build/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x50a: driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman: google.golang.org/grpc.(*Server).handleStream(0xc0002d64e0, 0xebf940, 0xc000001980, 0xc000192100, 0x0): driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman:         /home/colum/workspace/terraform/puppet/tmp/nomad-driver-podman-0.1.0/build/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xccb: driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000036040, 0xc0002d64e0, 0xebf940, 0xc000001980, 0xc000192100): driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman:         /home/colum/workspace/terraform/puppet/tmp/nomad-driver-podman-0.1.0/build/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa1: driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman: created by google.golang.org/grpc.(*Server).serveStreams.func1: driver=podman
 2020-08-18T20:56:32.745Z [DEBUG] client.driver_mgr.nomad-driver-podman:         /home/colum/workspace/terraform/puppet/tmp/nomad-driver-podman-0.1.0/build/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa1: driver=podman
 2020-08-18T20:56:32.746Z [DEBUG] client.driver_mgr: plugin process exited: driver=podman path=/opt/nomad/plugins/nomad-driver-podman pid=92308 error="exit status 2"
 2020-08-18T20:56:32.746Z [WARN]  client.driver_mgr: failed to reattach to plugin, starting new instance: driver=podman err="singleton plugin exited"
 2020-08-18T20:56:32.746Z [DEBUG] client.driver_mgr: starting plugin: driver=podman path=/opt/nomad/plugins/nomad-driver-podman args=[/opt/nomad/plugins/nomad-driver-podman]
 2020-08-18T20:56:32.746Z [WARN]  client.driver_mgr: received fingerprint error from driver: driver=podman error="plugin is shut down"

```

**Comment by jrasell** [comment]
Thanks for raising this issue @volfco. I will mark this accordingly so it can be investigated further.

**Comment by drewbailey** [comment]
Hey @volfco sorry that you ran into this. It seems as though this nil pointer was fixed in https://github.com/hashicorp/nomad-driver-podman/commit/b580f2d1#diff-d16a4232641fc7ed88a3737c22b4f54d7e03dd7fdf9053530fde70e5bca63fb1R349 please let us know if you run into this again.
